//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebAppTienda.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbTiendaOnlineBicicletasEntities : DbContext
    {
        public dbTiendaOnlineBicicletasEntities()
            : base("name=dbTiendaOnlineBicicletasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Carro> Tbl_Carro { get; set; }
        public virtual DbSet<Tbl_CarroStatus> Tbl_CarroStatus { get; set; }
        public virtual DbSet<Tbl_Categoria> Tbl_Categoria { get; set; }
        public virtual DbSet<Tbl_DetallesCompra> Tbl_DetallesCompra { get; set; }
        public virtual DbSet<Tbl_imagen> Tbl_imagen { get; set; }
        public virtual DbSet<Tbl_Miembro> Tbl_Miembro { get; set; }
        public virtual DbSet<Tbl_MiembroRol> Tbl_MiembroRol { get; set; }
        public virtual DbSet<Tbl_Producto> Tbl_Producto { get; set; }
        public virtual DbSet<Tbl_Proveedor> Tbl_Proveedor { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
    
        public virtual ObjectResult<GetBySearch_Result> GetBySearch(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBySearch_Result>("GetBySearch", searchParameter);
        }
    
        public virtual ObjectResult<GetCategoriaView_Result> GetCategoriaView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategoriaView_Result>("GetCategoriaView");
        }
    }
}
