//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebAppTienda.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DetallesCompra
    {
        public int DetallesCompraId { get; set; }
        public Nullable<int> ordenId { get; set; }
        public Nullable<int> MiembroId { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string TipoPago { get; set; }
    
        public virtual Tbl_Miembro Tbl_Miembro { get; set; }
    }
}
